const produtos = [
  {
    slug: "formula-negocio-online",
    name: "Fórmula Negócio Online",
    desc: "Marketing digital e afiliados",
    url: "formulanegocioonline.com.br",
    founder: "@alexvargas",
    nicho: "Marketing Digital",
    plataforma: "hotmart",
    receitaMin: 500000,
    receitaLabel: "R$ 500K+",
    alunos: 318247,
    crescimento: 12,
    receitaTotal: "R$ 4.200.000",
    mrr: "R$ 512.300,00",
    proposta: "O maior treinamento de marketing digital e afiliados do Brasil, focado em criar negócios lucrativos online do zero.",
    publico: "Empreendedores iniciantes que querem ganhar dinheiro na internet sem produto próprio.",
    problema: "Falta de método claro para monetizar no digital sem experiência prévia.",
    modelo: "B2C · Infoproduto único",
    techStack: ["Hotmart", "ActiveCampaign", "YouTube", "WhatsApp API"],
    tags: ["afiliados", "marketing digital", "renda extra", "infoproduto"],
  },
  {
    slug: "empiricus-academy",
    name: "Empiricus Academy",
    desc: "Finanças e investimentos",
    url: "empiricus.com.br/academy",
    founder: "@empiricus",
    nicho: "Finanças",
    plataforma: "hotmart",
    receitaMin: 400000,
    receitaLabel: "R$ 500K+",
    alunos: 207391,
    crescimento: 8,
    receitaTotal: "R$ 3.800.000",
    mrr: "R$ 420.000,00",
    proposta: "Formação completa em investimentos e finanças pessoais com análises de mercado em tempo real.",
    publico: "Investidores iniciantes e intermediários que querem independência financeira.",
    problema: "Desinformação financeira e falta de orientação prática para investir no Brasil.",
    modelo: "B2C · Assinatura mensal",
    techStack: ["Hotmart", "HubSpot", "Stripe", "Vimeo"],
    tags: ["finanças", "investimentos", "bolsa", "renda passiva"],
  },
  {
    slug: "devsuperior",
    name: "DevSuperior",
    desc: "Java e Spring Boot",
    url: "devsuperior.com.br",
    founder: "@nelio",
    nicho: "Programação",
    plataforma: "hotmart",
    receitaMin: 100000,
    receitaLabel: "R$ 100K–500K",
    alunos: 84823,
    crescimento: 31,
    receitaTotal: "R$ 980.000",
    mrr: "R$ 118.500,00",
    proposta: "Treinamento intensivo em Java, Spring Boot e React para devs que querem trabalhar em empresas grandes.",
    publico: "Desenvolvedores júnior e pleno que buscam especialização em back-end Java.",
    problema: "Falta de conteúdo prático e aprofundado em Java moderno no mercado brasileiro.",
    modelo: "B2C · Curso vitalício + mentorias",
    techStack: ["Hotmart", "Discord", "GitHub", "Notion"],
    tags: ["java", "spring boot", "back-end", "programação"],
  },
  {
    slug: "curso-em-video",
    name: "Curso em Vídeo",
    desc: "HTML, CSS, Python e mais",
    url: "cursoemvideo.com",
    founder: "@gustavoguanabara",
    nicho: "Programação",
    plataforma: "kiwify",
    receitaMin: 100000,
    receitaLabel: "R$ 100K–500K",
    alunos: 143618,
    crescimento: 5,
    receitaTotal: "R$ 750.000",
    mrr: "R$ 105.000,00",
    proposta: "Cursos gratuitos e pagos de programação com didática simples para quem está começando do zero.",
    publico: "Iniciantes absolutos em tecnologia, estudantes e profissionais em transição de carreira.",
    problema: "Barreira de entrada alta para aprender programação por conta própria.",
    modelo: "B2C · Freemium + certificações pagas",
    techStack: ["Kiwify", "YouTube", "Telegram", "Google Classroom"],
    tags: ["html", "css", "python", "iniciantes", "gratuito"],
  },
  {
    slug: "anon-financas-1",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_cr3",
    nicho: "Finanças",
    plataforma: "kiwify",
    receitaMin: 80000,
    receitaLabel: "R$ 50K–100K",
    alunos: 41744,
    crescimento: 64,
    receitaTotal: "—",
    mrr: "R$ 82.000,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "english-in-brazil",
    name: "English in Brazil",
    desc: "Inglês para brasileiros",
    url: "englishinbrazil.com.br",
    founder: "@rafaelgreca",
    nicho: "Idiomas",
    plataforma: "hotmart",
    receitaMin: 50000,
    receitaLabel: "R$ 50K–100K",
    alunos: 37892,
    crescimento: 18,
    receitaTotal: "R$ 320.000",
    mrr: "R$ 54.000,00",
    proposta: "Método brasileiro de inglês focado em fluência conversacional para adultos ocupados.",
    publico: "Profissionais brasileiros que precisam de inglês para trabalho ou intercâmbio.",
    problema: "Cursos de inglês genéricos que não consideram as dificuldades específicas do falante nativo de português.",
    modelo: "B2C · Curso + comunidade",
    techStack: ["Hotmart", "Zoom", "WhatsApp", "Canva"],
    tags: ["inglês", "idiomas", "conversação", "fluência"],
  },
  {
    slug: "anon-fitness",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_fit7",
    nicho: "Fitness",
    plataforma: "eduzz",
    receitaMin: 50000,
    receitaLabel: "R$ 50K–100K",
    alunos: 28671,
    crescimento: -8,
    receitaTotal: "—",
    mrr: "R$ 51.000,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "canva-do-zero",
    name: "Canva do Zero",
    desc: "Design para não-designers",
    url: "canvadozero.com.br",
    founder: "@laismoreira",
    nicho: "Design",
    plataforma: "kiwify",
    receitaMin: 30000,
    receitaLabel: "R$ 10K–50K",
    alunos: 19483,
    crescimento: 42,
    receitaTotal: "R$ 185.000",
    mrr: "R$ 31.200,00",
    proposta: "Curso prático de Canva para empreendedores criarem seus próprios materiais visuais sem contratar designer.",
    publico: "Pequenos empreendedores, freelancers e criadores de conteúdo sem experiência em design.",
    problema: "Alto custo de contratar designers para materiais simples de marketing digital.",
    modelo: "B2C · Curso vitalício",
    techStack: ["Kiwify", "Instagram", "Canva", "Notion"],
    tags: ["canva", "design", "empreendedorismo", "social media"],
  },
  {
    slug: "trafego-pago-pro",
    name: "Tráfego Pago Pro",
    desc: "Google Ads e Meta Ads",
    url: "trafegopagopro.com.br",
    founder: "@pedrosobral",
    nicho: "Marketing Digital",
    plataforma: "hotmart",
    receitaMin: 30000,
    receitaLabel: "R$ 10K–50K",
    alunos: 16847,
    crescimento: 22,
    receitaTotal: "R$ 142.000",
    mrr: "R$ 32.500,00",
    proposta: "Formação completa em gestão de tráfego pago para agências e freelancers que querem escalar clientes.",
    publico: "Gestores de tráfego iniciantes e agências digitais em crescimento.",
    problema: "Falta de método sistemático para escalar resultados em tráfego pago com ROI positivo.",
    modelo: "B2C · Mentoria em grupo + curso",
    techStack: ["Hotmart", "Google Ads", "Meta Ads", "ActiveCampaign"],
    tags: ["tráfego pago", "google ads", "meta ads", "performance"],
  },
  {
    slug: "anon-mkt",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_mkt12",
    nicho: "Marketing Digital",
    plataforma: "monetizze",
    receitaMin: 25000,
    receitaLabel: "R$ 10K–50K",
    alunos: 9731,
    crescimento: 115,
    receitaTotal: "—",
    mrr: "R$ 26.500,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "culinaria-fit-brasil",
    name: "Culinária Fit Brasil",
    desc: "Receitas saudáveis e práticas",
    url: "culinariafitbrasil.com.br",
    founder: "@anacunha",
    nicho: "Culinária",
    plataforma: "hotmart",
    receitaMin: 20000,
    receitaLabel: "R$ 10K–50K",
    alunos: 13047,
    crescimento: 9,
    receitaTotal: "R$ 98.000",
    mrr: "R$ 21.000,00",
    proposta: "Receitas fit rápidas e acessíveis para quem quer emagrecer sem abrir mão do sabor.",
    publico: "Mulheres entre 25–45 anos em busca de alimentação saudável no dia a dia.",
    problema: "Receitas fit complexas, caras e sem praticidade para a rotina brasileira.",
    modelo: "B2C · Assinatura mensal",
    techStack: ["Hotmart", "Instagram", "WhatsApp", "Canva"],
    tags: ["fitness", "culinária", "emagrecer", "receitas"],
  },
  {
    slug: "excel-expert",
    name: "Excel Expert",
    desc: "Excel do básico ao avançado",
    url: "excelexpert.com.br",
    founder: "@tiagosouza",
    nicho: "Produtividade",
    plataforma: "eduzz",
    receitaMin: 15000,
    receitaLabel: "R$ 10K–50K",
    alunos: 11203,
    crescimento: -3,
    receitaTotal: "R$ 72.000",
    mrr: "R$ 15.800,00",
    proposta: "Domine o Excel com aulas práticas focadas no dia a dia corporativo e análise de dados.",
    publico: "Analistas, assistentes administrativos e gestores que usam Excel no trabalho.",
    problema: "Profissionais perdem horas em tarefas que o Excel resolve em minutos quando bem utilizado.",
    modelo: "B2C · Curso vitalício",
    techStack: ["Eduzz", "YouTube", "Telegram", "Google Sheets"],
    tags: ["excel", "planilhas", "produtividade", "office"],
  },
  {
    slug: "anon-programacao",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_edu9",
    nicho: "Programação",
    plataforma: "kiwify",
    receitaMin: 12000,
    receitaLabel: "R$ 10K–50K",
    alunos: 6634,
    crescimento: 88,
    receitaTotal: "—",
    mrr: "R$ 12.000,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "fotografia-lucrativa",
    name: "Fotografia Lucrativa",
    desc: "Fotografia e edição de retratos",
    url: "fotografialucrativa.com.br",
    founder: "@brunocampos",
    nicho: "Fotografia",
    plataforma: "hotmart",
    receitaMin: 10000,
    receitaLabel: "R$ 10K–50K",
    alunos: 7219,
    crescimento: 14,
    receitaTotal: "R$ 58.000",
    mrr: "R$ 10.500,00",
    proposta: "Transforme sua câmera em fonte de renda com técnicas profissionais de fotografia e edição.",
    publico: "Fotógrafos amadores e profissionais autônomos que querem monetizar suas habilidades.",
    problema: "Fotógrafos talentosos sem técnica de precificação e captação de clientes.",
    modelo: "B2C · Curso + comunidade VIP",
    techStack: ["Hotmart", "Lightroom", "Instagram", "Canva"],
    tags: ["fotografia", "edição", "lightroom", "freelancer"],
  },
  {
    slug: "react-na-pratica",
    name: "React na Prática",
    desc: "React, Next.js e TypeScript",
    url: "reactnapratica.dev",
    founder: "@diegofernandes",
    nicho: "Programação",
    plataforma: "kiwify",
    receitaMin: 8000,
    receitaLabel: "R$ 1K–10K",
    alunos: 4176,
    novo: true,
    crescimento: 56,
    receitaTotal: "R$ 32.000",
    mrr: "R$ 8.200,00",
    proposta: "Aprenda React, Next.js e TypeScript construindo projetos reais usados por empresas.",
    publico: "Desenvolvedores front-end que querem migrar para React ou aprofundar conhecimento em Next.js.",
    problema: "Tutoriais de React ensinam conceitos isolados sem conexão com projetos reais de mercado.",
    modelo: "B2C · Curso vitalício + updates",
    techStack: ["Kiwify", "GitHub", "Discord", "Notion"],
    tags: ["react", "next.js", "typescript", "front-end"],
  },
  {
    slug: "anon-financas-2",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_fin2",
    nicho: "Finanças",
    plataforma: "hotmart",
    receitaMin: 7000,
    receitaLabel: "R$ 1K–10K",
    alunos: 3084,
    crescimento: -15,
    receitaTotal: "—",
    mrr: "R$ 7.000,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "coaching-de-carreira",
    name: "Coaching de Carreira BR",
    desc: "Recolocação e liderança",
    url: "coachingdecarreira.com.br",
    founder: "@mariafernanda",
    nicho: "Carreira",
    plataforma: "monetizze",
    receitaMin: 5000,
    receitaLabel: "R$ 1K–10K",
    alunos: 2193,
    crescimento: 7,
    receitaTotal: "R$ 19.000",
    mrr: "R$ 5.400,00",
    proposta: "Programa de aceleração de carreira para profissionais que querem liderança e recolocação rápida.",
    publico: "Profissionais entre 28–45 anos em busca de promoção ou mudança de área.",
    problema: "Falta de direcionamento estratégico para crescer profissionalmente no mercado competitivo.",
    modelo: "B2C · Mentoria individual + grupo",
    techStack: ["Monetizze", "Zoom", "Notion", "WhatsApp"],
    tags: ["carreira", "liderança", "recolocação", "coaching"],
  },
  {
    slug: "yoga-bem-estar",
    name: "Yoga & Bem-estar",
    desc: "Yoga para iniciantes",
    url: "yogabemestar.com.br",
    founder: "@juliana.yogi",
    nicho: "Fitness",
    plataforma: "eduzz",
    receitaMin: 3000,
    receitaLabel: "R$ 1K–10K",
    alunos: 1847,
    novo: true,
    crescimento: 33,
    receitaTotal: "R$ 11.000",
    mrr: "R$ 3.200,00",
    proposta: "Programa de yoga online para iniciantes que querem reduzir estresse e ganhar flexibilidade em 30 dias.",
    publico: "Adultos sedentários e estressados que nunca praticaram yoga antes.",
    problema: "Aulas de yoga presenciais caras e com horários incompatíveis com a rotina moderna.",
    modelo: "B2C · Assinatura mensal",
    techStack: ["Eduzz", "Vimeo", "WhatsApp", "Canva"],
    tags: ["yoga", "meditação", "bem-estar", "iniciantes"],
  },
  {
    slug: "anon-design",
    name: "Produto Anônimo",
    desc: "—",
    url: null,
    founder: "@anon_ds5",
    nicho: "Design",
    plataforma: "kiwify",
    receitaMin: 2000,
    receitaLabel: "R$ 1K–10K",
    alunos: 937,
    crescimento: 200,
    receitaTotal: "—",
    mrr: "R$ 2.000,00",
    proposta: "—",
    publico: "—",
    problema: "—",
    modelo: "—",
    techStack: [],
    tags: ["anônimo"],
    anon: true,
  },
  {
    slug: "escrita-criativa",
    name: "Escrita Criativa Online",
    desc: "Storytelling e copywriting",
    url: "escritacriativa.com.br",
    founder: "@claudiafaria",
    nicho: "Escrita",
    plataforma: "hotmart",
    receitaMin: 1000,
    receitaLabel: "R$ 1K–10K",
    alunos: 613,
    novo: true,
    crescimento: 25,
    receitaTotal: "R$ 4.200",
    mrr: "R$ 1.100,00",
    proposta: "Aprenda a escrever histórias que vendem: storytelling e copywriting para criadores de conteúdo.",
    publico: "Criadores de conteúdo, blogueiros e empreendedores que querem comunicar melhor.",
    problema: "Profissionais com boas ideias mas que não conseguem transformá-las em textos persuasivos.",
    modelo: "B2C · Curso vitalício",
    techStack: ["Hotmart", "Substack", "Instagram", "Notion"],
    tags: ["copywriting", "storytelling", "escrita", "conteúdo"],
  },
];
